### ISSUE TITLE
Boards Manager support JSON file is missing

### ISSUE THREAD

**Issue by per1234** [d00616/arduino-nRF5#5]
The Boards Manager installation [instructions ](https://github.com/d00616/arduino-nRF5#board-manager)indicate there should be a `gh-pages` branch with the file package_nRF5e_boards_index.json but this branch does not exist.

This issue causes Travis CI builds to fail in the arduino-NVM repository. For example:
https://travis-ci.org/d00616/arduino-NVM/builds/271302627
though in that case the missing file is named package_nRF5_boards_index.json.

**Comment by d00616** [comment]
Thank you. At the moment I have no plans to maintain that fork, I think it's not the right way. I have changed the default repository.

I use my nRF5 boards with MySensors only. I have added all functionally (OUTPUT modes, WDT) to [MySensors](https://www.openhardware.io/view/376/MySensors-NRF5-Platform) and https://github.com/mysensors/ArduinoHwNRF5
